name: Default Template
markdown: redcarpet
pygments: true

# Modify these values
# local host is used to debug when a local server is running
#  url: http://localhost:4000
url: http://GT-MINED.github.io
# Repository Name
baseurl: /Matlab-Bootstrap-GH
# default image location
imgbase: /assets

# User information
user: "Mined Research Group"

email: tony.fast@gmail.com
# Get your disqus username at www.disqus.com
disqus: 
# A global comment system
# www.disqus.com
twitter: 
linkedin: 
github: GT-MINED
slideshare: 
gravatar:
  hash: 
